### ISSUE TITLE
Could not update axios

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/megalodon#1060]
```
$ node dist/pleroma/favourite.js 
(node:161103) UnhandledPromiseRejectionWarning: TypeError: config.cancelToken.subscribe is not a function
    at dispatchHttpRequest (/home/h3poteto/src/github.com/h3poteto/megalodon/node_modules/axios/lib/adapters/http.js:347:48)
    at new Promise (<anonymous>)
    at httpAdapter (/home/h3poteto/src/github.com/h3poteto/megalodon/node_modules/axios/lib/adapters/http.js:48:10)
    at dispatchRequest (/home/h3poteto/src/github.com/h3poteto/megalodon/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/h3poteto/src/github.com/h3poteto/megalodon/node_modules/axios/lib/core/Axios.js:108:15)
    at Axios.<computed> [as get] (/home/h3poteto/src/github.com/h3poteto/megalodon/node_modules/axios/lib/core/Axios.js:129:17)
    at Function.wrap [as get] (/home/h3poteto/src/github.com/h3poteto/megalodon/node_modules/axios/lib/helpers/bind.js:9:15)
    at Client.<anonymous> (/home/h3poteto/src/github.com/h3poteto/megalodon/megalodon/lib/src/pleroma/api_client.js:262:30)
    at step (/home/h3poteto/src/github.com/h3poteto/megalodon/megalodon/lib/src/pleroma/api_client.js:33:23)
    at Object.next (/home/h3poteto/src/github.com/h3poteto/megalodon/megalodon/lib/src/pleroma/api_client.js:14:53)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:161103) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:161103) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by h3poteto** [comment]
Use `abort-controller` to cancel requests: https://axios-http.com/docs/cancellation
