### ISSUE TITLE
Unhandled exception when close connection

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/megalodon#115]
The exception has occur, after I stop the server when I run streaming with websocekt.

```
[2019-12-16 01:13:39.877] [error] Error: WebSocket was closed before the connection was established
    at WebSocket.close (/opt/Whalebird/resources/app.asar/node_modules/ws/lib/websocket.js:219:14)
    at WebSocket._resetConnection (/opt/Whalebird/resources/app.asar/node_modules/megalodon/lib/src/web_socket.js:65:26)
    at WebSocket.stop (/opt/Whalebird/resources/app.asar/node_modules/megalodon/lib/src/web_socket.js:60:14)
    at e.stop (/opt/Whalebird/resources/app.asar/dist/electron/main.js:1:28962)
    at EventEmitter.<anonymous> (/opt/Whalebird/resources/app.asar/dist/electron/main.js:1:53683)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (/opt/Whalebird/resources/electron.asar/browser/api/web-contents.js:335:21)
    at WebContents.emit (events.js:200:13)
```

**Comment by h3poteto** [comment]
![Screenshot from 2019-12-17 11-14-53](https://user-images.githubusercontent.com/4631959/70959089-8c6c3c00-20be-11ea-9ee5-5efd8557de98.png)
![Screenshot from 2019-12-17 11-15-24](https://user-images.githubusercontent.com/4631959/70959096-8f672c80-20be-11ea-8a3e-36155fb6b427.png)
